# Render 배포 설정 - Python 3.8.18 강제 고정
services:
  - type: web
    name: hyojin-ai-mvp
    runtime: python
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: PORT
        generateValue: true
